In [211]:
import pandas as pd
import numpy as np
import json
import ast
import black

#%load_ext jupyter_black

In [227]:
#raw_data = pd.read_csv("raw_data_2023-06-16_18:39:47.csv", index_col=0)
raw_data = pd.read_csv("raw_data_2023-06-25_22:31:05.csv", index_col=0)

In [230]:
raw_data

,raw_data,dump_time
seller_name,,
Piscine Zyke,"{'product_1': {'ean': '6942138982435', 'title'...",1.687725e+09
RAVIDAY,"{'product_1': {'ean': '6941057415499', 'title'...",1.687725e+09
Mondo Top,"{'product_1': {'ean': '6941812714881', 'title'...",1.687725e+09
Doctor Brandt,"{'product_1': {'ean': '0045496453596', 'title'...",1.687725e+09
RELAX MoMa,"{'product_1': {'ean': '6942138975895', 'title'...",1.687725e+09
BESTWAY FRANCE,"{'product_1': {'ean': '3760275217523', 'title'...",1.687725e+09
123PISCINES,"{'product_1': {'ean': '3760275217523', 'title'...",1.687725e+09
Best of Robots,"{'product_1': {'ean': '6942138982435', 'title'...",1.687725e+09
Centrale Brico,"{'product_1': {'ean': '6942138982435', 'title'...",1.687725e+09
Outillage online,"{'product_1': {'ean': '6942138982435', 'title'...",1.687725e+09

In [222]:
len(all_seller_product)

8

for seller in all_seller_product[1]

In [224]:
all_seller_product = raw_data["raw_data"].values
ast.literal_eval(all_seller_product[1])["product_3"]

{'ean': '0196378567419',
 'title': 'PC Portable LENOVO Ideapad 3 15ALC6 - 15,6" FHD - AMD Ryzen 5-5500U - RAM 8Go - 512Go SSD - AZERTY',
 'seller_price': '518\n€04',
 'seller_name_fp': 'ENTER-WEB',
 'captcha': '',
 'seller_listing': '/mp-228394-len0196378567419.html?Filter=New',
 'product_image': ['https://www.cdiscount.com/pdt2/4/1/9/1/065x065/len0196378567419/rw/pc-portable-lenovo-ideapad-3-15alc6-15-6-fhd.jpg',
  'https://www.cdiscount.com/pdt2/4/1/9/2/065x065/len0196378567419/rw/pc-portable-lenovo-ideapad-3-15alc6-15-6-fhd.jpg',
  'https://www.cdiscount.com/pdt2/4/1/9/3/065x065/len0196378567419/rw/pc-portable-lenovo-ideapad-3-15alc6-15-6-fhd.jpg',
  'https://www.cdiscount.com/pdt2/4/1/9/4/065x065/len0196378567419/rw/pc-portable-lenovo-ideapad-3-15alc6-15-6-fhd.jpg',
  'https://www.cdiscount.com/pdt2/4/1/9/5/065x065/len0196378567419/rw/pc-portable-lenovo-ideapad-3-15alc6-15-6-fhd.jpg',
  'https://www.cdiscount.com/pdt2/4/1/9/6/065x065/len0196378567419/rw/pc-portable-lenovo-ideapad-3-15alc6-15-6-fhd.jpg'],
 'description': ['Lenovo IdeaPad 3 15ALC6 82KU - Ryzen 5 5500U / 2.1 GHz - Win 11 Home - Radeon Graphics - 8 Go RAM - 512 Go SSD NVMe - 15.6" TN 1920 x 1080 (Full HD) - Wi-Fi 6 - gris arctique - clavier : Français',
  '',
  'PUBLICITÉ',
  'Tableau de caractéristiques du produit',
  'Caractéristique',
  'Description',
  'Informations générales sur le produit',
  'Marque',
  'LENOVO',
  '',
  'Nom du produit',
  'PC Portable LENOVO Ideapad 3 15ALC6 - 15,6" FHD -',
  'Catégorie',
  'ORDINATEUR PORTABLE',
  'Référence',
  '82KU01PEFR',
  'Informations sur le produit',
  'Sous-état',
  'Neuf',
  'Indice de réparabilité',
  '7,8',
  'Général',
  "Système d'exploitation",
  'Windows 11 Home - français',
  'Type de Produit',
  'Ordinateur portable',
  'Processeur / Chipset',
  'CPU',
  'AMD Ryzen 5 5500U / 2.1 GHz',
  'Nombre de coeurs',
  '6 coeurs',
  'Cache',
  'L3 - 8 Mo',
  'Vitesse maximale en mode Turbo',
  '4 GHz',
  'Fonctions',
  'Contrôleur de mémoire intégré',
  'Affichage',
  'Type',
  '15.6" - TN',
  'Technologie de rétroéclairage LCD',
  'Rétroéclairage par LED',
  'Résolution',
  '1920 x 1080 (Full HD)',
  'Fonctions',
  'Anti-éblouissement',
  'Grand écran',
  'Oui',
  "Format de l'image",
  '16:9',
  "Luminosité de l'image",
  '250 cd/m²',
  'Gamme de couleurs',
  '45% NTSC',
  'Stockage',
  'Stockage principal',
  '512 Go SSD M.2 2280 PCIe 3.0 x4 - NVM Express (NVMe)',
  'Mémoire',
  'RAM',
  '8 Go (1 x 4 Go + 4 Go (soudé))',
  'Technologie',
  'DDR4 SDRAM',
  'Vitesse',
  '3200 MHz',
  'RAM max prise en charge',
  '12 Go',
  'Format',
  'SO DIMM 260 broches',
  "Nombre d'emplacements",
  '1',
  'Emplacements mémoire libre',
  '0',
  'Audio & vidéo',
  'Processeur graphique',
  'AMD Radeon Graphics',
  "Technologie d'allocation de mémoire",
  'Mémoire vidéo partagée (UMA)',
  'Codec',
  'Realtek ALC3287',
  'Caméra',
  'Oui - 720p',
  'Caractéristiques de la caméra',
  'Volet de discretion',
  'Son',
  'Haut-parleurs stéréo, double tableau de microphone',
  'Normes de conformité',
  'Audio haute définition, Dolby Audio',
  'Maximum de moniteurs supportés',
  '1 moniteur(s) externe(s)',
  'Communications',
  'Sans fil',
  '802.11a/b/g/n/ac/ax, Bluetooth 5.1',
  'Contrôleur sans fil',
  'M.2 Card',
  'Fonctions',
  'Double flux (2 x 2)',
  'Connexions & extension',
  'Lecteur de carte mémoire',
  '4 en 1 (carte SD, MultiMediaCard, carte SDHC, carte SDXC)',
  'Interfaces',
  'USB 2.0',
  'USB 3.2 Gen 1',
  'USB-C 3.2 Gen 1',
  'HDMI',
  'Prise combo casque/microphone',
  'Logiciels',
  'Logiciel(s) inclus',
  "Microsoft Office (version d'évaluation)",
  'Entrée',
  'Type',
  'Clavier, Pavé tactile',
  'Caractéristiques',
  'Pavé tactile multi-touches, pavé tactile sans bouton, pavé tactile de précision',
  'Disposition du clavier',
  'Français',
  'Batterie',
  'Technologie',
  'Lithium-polymère',
  'Capacité',
  '38 Wh',
  'Durée de fonctionnement',
  "Jusqu'à 9 heures",
  'Divers',
  'Couleur',
  'Gris arctique',
  'Caractéristiques',
  'Mot de passe administrateur, accès sécurisé au disque dur, mot de passe à la mise sous tension',
  'Localisation',
  'Langue : français / région : France',
  'Sécurité',
  'Firmware Trusted Platform Module (TPM 2.0) Security Chip',
  'Programme de ventes par le fabricant',
  'TopSeller',
  'Normes de conformité',
  'RoHS, Energy-Related Products (ErP) Lot 3',
  'Matière du boitier',
  'ABS polycarbonate',
  'Finition de surface',
  'IMR',
  'Dimensions et poids',
  'Poids',
  '1.65 kg',
  'Dimensions (LxPxH)',
  '35.92 cm x 23.65 cm x 1.99 cm',
  'Garantie du fabricant',
  'Service et maintenance',
  'Garantie limitée - 2 ans - enlèvement et retour',
  'Garantie limitée - batterie - 1 an',
  'Adaptateur CA',
  'Entrée',
  'CA 100-240 V (50/60 Hz)',
  'Sortie',
  '65 Watt',
  'Caractéristiques d’environnement',
  "Taux d'humidité en fonctionnement",
  '8 - 95%',
  'Température minimale de fonctionnement',
  '5 °C',
  'Température maximale de fonctionnement',
  '35 °C',
  'Attributs de recherche',
  'Stockage optique|Type de lecteur',
  'Pas de disque optique',
  'Vos garanties incluses',
  'Garantie (²)',
  '2 ans',
  'Observations',
  'Dans le cas où une garantie commerciale est proposée par le vendeur, celle-ci ne fait pas obstacle à',
  ''],
 'page_seller': '/mpvv-1946-ENTER-WEB.html',
 'offer_count': '8 neufs',
 'offers': [{'seller_price': '499\n€99',
   'seller_name': 'Cdiscount',
   'shipping_rate_price': 'Livraison à domicile ou en point retrait',
   'expedition_country': '',
   'sales_realized': '',
   'seller_rating': '',
   'state': 'Neuf'},
  {'seller_price': '499\n€00',
   'seller_name': 'NDR STORE',
   'shipping_rate_price': 'Gratuit',
   'expedition_country': 'FRANCE',
   'sales_realized': '122',
   'seller_rating': 'Évaluations(19                            avis)\n4,4/5',
   'state': 'Neuf'},
  {'seller_price': '518\n€04',
   'seller_name': 'ENTER-WEB',
   'shipping_rate_price': 'Gratuit',
   'expedition_country': 'FRANCE',
   'sales_realized': '626',
   'seller_rating': 'Évaluations(504                            avis)\n4,5/5',
   'state': 'Neuf'},
  {'seller_price': '698\n€80',
   'seller_name': 'GLD Group',
   'shipping_rate_price': 'Gratuit',
   'expedition_country': 'FRANCE',
   'sales_realized': '13',
   'seller_rating': 'Évaluation(0                            avis)\nAucun avis',
   'state': 'Neuf'},
  {'seller_price': '708\n€21',
   'seller_name': 'TOPBIZ',
   'shipping_rate_price': 'Gratuit',
   'expedition_country': 'FRANCE',
   'sales_realized': '20837',
   'seller_rating': 'Évaluations(4547                            avis)\n4,5/5',
   'state': 'Neuf'},
  {'seller_price': '759\n€54',
   'seller_name': 'ADMI',
   'shipping_rate_price': 'Gratuit',
   'expedition_country': 'FRANCE',
   'sales_realized': '5260',
   'seller_rating': 'Évaluations(2069                            avis)\n4,6/5',
   'state': 'Neuf'},
  {'seller_price': '749\n€96',
   'seller_name': 'PCANDCO',
   'shipping_rate_price': '10,90€',
   'expedition_country': 'FRANCE',
   'sales_realized': '286',
   'seller_rating': 'Évaluation(1                            avis)\n5/5',
   'state': 'Neuf'},
  {'seller_price': '906\n€06',
   'seller_name': 'FRANCE/RENEW',
   'shipping_rate_price': 'Gratuit',
   'expedition_country': 'FRANCE',
   'sales_realized': '177',
   'seller_rating': 'Évaluations(13                            avis)\n4,4/5',
   'state': 'Neuf'}]}

In [53]:
def normalize_shipping_price(raw_shipping_price):
    try:
        return float(raw_shipping_price.replace(",", ".").replace("€", "").replace("Gratuit", '0'))
    except Exception as e:
        return 0

all_seller_product

In [63]:
info_all_seller_product = []
product_check = set()
product_without_concurrent = []

for all_product_seller in all_seller_product:
    dict_all_product_seller = ast.literal_eval(all_product_seller)
    for product in dict_all_product_seller.values():
        try:
            info_product = {}
            ean = product["ean"]
            price = product["seller_price"]
            name_seller = product["seller_name_fp"]
            if ean in product_check:
                continue
            # print(name_seller)
            try:
                others_offer = product["offers"]
                pass
            except Exception:
                product_without_concurrent.append(product)
                # print(product["title"])
                # print(product["seller_price"])
                # print("ici", name_seller)
                # print(ean)
                # print("----------------------------")
                continue
            if name_seller == "":
                price_site_seller = price
                all_price_other_seller = {}
                for info_other_product in others_offer:
                    if (
                        info_other_product["seller_name"].lower().replace(" ", "")
                        == "cdiscount"
                    ):
                        continue
                    else:
                        all_price_other_seller[
                            info_other_product["seller_name"]
                        ] = {"price": float(
                            info_other_product["seller_price"]
                            .replace("\n", ".")
                            .replace("€", "")),
                             "shipping_rate_price": normalize_shipping_price(info_other_product["shipping_rate_price"])
                            }
                info_product["ean"] = ean
                info_product["list_other_price"] = all_price_other_seller
                product_check.add(ean)
                continue
            else:
                all_price_other_seller = {}
                for info_other_product in others_offer:
                    if (
                        info_other_product["seller_name"].lower().replace(" ", "")
                        == "cdiscount"
                    ):
                        price_site_seller = float(
                            info_other_product["seller_price"]
                            .replace("\n", ".")
                            .replace("€", "")
                        )
                        info_product["price_site_seller"] = price_site_seller
                    else:
                        all_price_other_seller[
                            info_other_product["seller_name"]
                        ] = {"price": float(
                            info_other_product["seller_price"]
                            .replace("\n", ".")
                            .replace("€", "")),
                             "shipping_rate_price": normalize_shipping_price(info_other_product["shipping_rate_price"])
                            }
                info_product["ean"] = ean
                info_product["list_other_price"] = all_price_other_seller
                product_check.add(ean)
            info_all_seller_product.append(info_product)
        except Exception:
            pass

In [225]:
info_all_seller_product

[{'price_site_seller': 499.99,
  'ean': '0196378567419',
  'list_other_price': {'NDR STORE': {'price': 499.0,
    'shipping_rate_price': 0.0},
   'ENTER-WEB': {'price': 518.04, 'shipping_rate_price': 0.0},
   'GLD Group': {'price': 698.8, 'shipping_rate_price': 0.0},
   'TOPBIZ': {'price': 708.21, 'shipping_rate_price': 0.0},
   'ADMI': {'price': 759.54, 'shipping_rate_price': 0.0},
   'PCANDCO': {'price': 749.96, 'shipping_rate_price': 10.9},
   'FRANCE/RENEW': {'price': 906.06, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 499.99,
  'ean': '0196119451311',
  'list_other_price': {'ENTER-WEB': {'price': 701.85,
    'shipping_rate_price': 0.0}}},
 {'price_site_seller': 999.99,
  'ean': '4711121242069',
  'list_other_price': {'GLD Group': {'price': 1469.9,
    'shipping_rate_price': 0.0}}},
 {'price_site_seller': 99.99,
  'ean': '3701542101732',
  'list_other_price': {'Trending Utopic': {'price': 123.1,
    'shipping_rate_price': 0.0},
   'LMD Distribution': {'price': 128.98, 'shipping_rate_price': 0.0},
   'Fexy-shop': {'price': 129.45, 'shipping_rate_price': 0.0},
   'Detoutpourmoinscher': {'price': 133.3, 'shipping_rate_price': 0.0},
   'GLD Group': {'price': 133.5, 'shipping_rate_price': 0.0},
   'Global Market 54': {'price': 142.6, 'shipping_rate_price': 0.0},
   'Microlorge': {'price': 167.44, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 239.99,
  'ean': '3612408836791',
  'list_other_price': {'yes-Promo': {'price': 268.79,
    'shipping_rate_price': 0.0},
   'LMD Distribution': {'price': 277.98, 'shipping_rate_price': 0.0},
   'Trending Utopic': {'price': 286.4, 'shipping_rate_price': 0.0},
   'GLD Group': {'price': 300.0, 'shipping_rate_price': 0.0},
   'Fexy-shop': {'price': 302.72, 'shipping_rate_price': 0.0},
   'eurekabelle': {'price': 303.03, 'shipping_rate_price': 0.0},
   'Global Market 54': {'price': 303.1, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 199.99,
  'ean': '4710886672340',
  'list_other_price': {'RefurbPlanet': {'price': 299.9,
    'shipping_rate_price': 10.0},
   'GLD Group': {'price': 324.6, 'shipping_rate_price': 0.0},
   'Microlorge': {'price': 487.86, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 20.99,
  'ean': '3612408913485',
  'list_other_price': {'yes-Promo': {'price': 33.92,
    'shipping_rate_price': 0.0},
   'Trending Utopic': {'price': 37.1, 'shipping_rate_price': 0.0},
   'Fexy-shop': {'price': 37.66, 'shipping_rate_price': 0.0},
   'Microlorge': {'price': 39.54, 'shipping_rate_price': 0.0},
   'GLD Group': {'price': 41.8, 'shipping_rate_price': 0.0},
   'eurekabelle': {'price': 42.07, 'shipping_rate_price': 0.0},
   'Global Market 54': {'price': 42.1, 'shipping_rate_price': 0.0},
   'LMD Distribution': {'price': 56.98, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 279.99,
  'ean': '8003437604867',
  'list_other_price': {'realmarket': {'price': 278.99,
    'shipping_rate_price': 0.0},
   'ASdiscount': {'price': 282.27, 'shipping_rate_price': 0.0},
   'ZOOMICI': {'price': 308.66, 'shipping_rate_price': 0.0},
   'Mon eDeal': {'price': 309.9, 'shipping_rate_price': 0.0},
   'Soderus': {'price': 319.59, 'shipping_rate_price': 0.0},
   'Fexy-shop': {'price': 336.52, 'shipping_rate_price': 0.0},
   'DistribNet': {'price': 342.46, 'shipping_rate_price': 0.0},
   'LMD Distribution': {'price': 343.98, 'shipping_rate_price': 0.0},
   'Electropolis': {'price': 349.94, 'shipping_rate_price': 9.0}}},
 {'price_site_seller': 749.99,
  'ean': '0196786486111',
  'list_other_price': {'GLD Group': {'price': 1065.3,
    'shipping_rate_price': 0.0}}},
 {'price_site_seller': 459.99,
  'ean': '3700342444391',
  'list_other_price': {'Nouveaux Marchands': {'price': 299.99,
    'shipping_rate_price': 0.0},
   'yes-Promo': {'price': 531.86, 'shipping_rate_price': 0.0},
   'Trending Utopic': {'price': 554.1, 'shipping_rate_price': 0.0},
   'LMD Distribution': {'price': 555.98, 'shipping_rate_price': 0.0},
   'Fexy-shop': {'price': 565.35, 'shipping_rate_price': 0.0},
   'GLD Group': {'price': 580.5, 'shipping_rate_price': 0.0},
   'lacavernedesprix': {'price': 636.59, 'shipping_rate_price': 10.68},
   'BlackMarketplace': {'price': 676.5, 'shipping_rate_price': 0.0},
   'Microlorge': {'price': 804.05, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 239.99,
  'ean': '3660767979482',
  'list_other_price': {'Fexy-shop': {'price': 291.22,
    'shipping_rate_price': 0.0},
   'DistribNet': {'price': 296.0, 'shipping_rate_price': 0.0},
   'LMD Distribution': {'price': 297.98, 'shipping_rate_price': 0.0},
   'Full Line OU': {'price': 310.76, 'shipping_rate_price': 0.0},
   'Trending Utopic': {'price': 310.8, 'shipping_rate_price': 0.0},
   'GLD Group': {'price': 325.6, 'shipping_rate_price': 0.0},
   'BlackMarketplace': {'price': 348.2, 'shipping_rate_price': 0.0},
   'Microlorge': {'price': 356.3, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 119.99,
  'ean': '8806090397424',
  'list_other_price': {'Boutique du Der': {'price': 154.0,
    'shipping_rate_price': 0.0},
   'GLD Group': {'price': 171.7, 'shipping_rate_price': 0.0},
   'Global Market 54': {'price': 173.4, 'shipping_rate_price': 0.0},
   'BlackMarketplace': {'price': 183.6, 'shipping_rate_price': 0.0},
   'Microlorge': {'price': 222.63, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 40.49,
  'ean': '7290112634580',
  'list_other_price': {'Full Line OU': {'price': 61.92,
    'shipping_rate_price': 0.0},
   'Trending Utopic': {'price': 64.3, 'shipping_rate_price': 0.0},
   'Just shopping': {'price': 70.8, 'shipping_rate_price': 0.0},
   'Microlorge': {'price': 72.09, 'shipping_rate_price': 0.0},
   'GLD Group': {'price': 73.2, 'shipping_rate_price': 0.0},
   'eurekabelle': {'price': 73.73, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 299.99,
  'ean': '0196786486081',
  'list_other_price': {'Microlorge': {'price': 800.05,
    'shipping_rate_price': 0.0}}},
 {'price_site_seller': 398.9,
  'ean': '6941057408576',
  'list_other_price': {'Votre-Plancha': {'price': 398.02,
    'shipping_rate_price': 0.0},
   'RAVIDAY': {'price': 399.0, 'shipping_rate_price': 0.0},
   'JARDIDECO': {'price': 454.0, 'shipping_rate_price': 0.0},
   'Eazryo Sarls': {'price': 474.92, 'shipping_rate_price': 0.0},
   'LE DEPOT BAILLEUL': {'price': 562.34, 'shipping_rate_price': 0.0},
   'eFitness': {'price': 500.53, 'shipping_rate_price': 99.99},
   'AC-Deco': {'price': 699.29, 'shipping_rate_price': 0.0},
   'brico-travo': {'price': 744.14, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 259.99,
  'ean': '8806088757261',
  'list_other_price': {'Stacca': {'price': 286.0, 'shipping_rate_price': 0.0},
   'Icoza': {'price': 301.64, 'shipping_rate_price': 0.0},
   'UBALDI': {'price': 304.0, 'shipping_rate_price': 0.0},
   'LMD Distribution': {'price': 307.98, 'shipping_rate_price': 0.0},
   'DistribNet': {'price': 318.43, 'shipping_rate_price': 0.0},
   'Restock System': {'price': 331.7, 'shipping_rate_price': 0.0},
   'Nouveaux Marchands': {'price': 331.78, 'shipping_rate_price': 0.0},
   'Fexy-shop': {'price': 334.31, 'shipping_rate_price': 0.0},
   'Full Line OU': {'price': 334.31, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 63.99,
  'ean': '0195161618109',
  'list_other_price': {'Vpc Boost': {'price': 70.81,
    'shipping_rate_price': 0.0},
   'ZOOMICI': {'price': 71.99, 'shipping_rate_price': 0.0},
   'Fexy-shop': {'price': 73.34, 'shipping_rate_price': 0.0},
   'ASdiscount': {'price': 75.9, 'shipping_rate_price': 0.0},
   'yes-Promo': {'price': 78.91, 'shipping_rate_price': 0.0},
   'Yeppon': {'price': 79.99, 'shipping_rate_price': 0.0},
   'Trending Utopic': {'price': 80.1, 'shipping_rate_price': 0.0},
   'Soderus': {'price': 84.81, 'shipping_rate_price': 0.0},
   'GLD Group': {'price': 86.8, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 58.99,
  'ean': '8720389000041',
  'list_other_price': {'yes-Promo': {'price': 78.71,
    'shipping_rate_price': 0.0},
   'Full Line OU': {'price': 81.99, 'shipping_rate_price': 0.0},
   'Trending Utopic': {'price': 83.6, 'shipping_rate_price': 0.0},
   'Fexy-shop': {'price': 88.76, 'shipping_rate_price': 0.0},
   'GLD Group': {'price': 91.4, 'shipping_rate_price': 0.0},
   'BlackMarketplace': {'price': 91.9, 'shipping_rate_price': 0.0},
   'Just shopping': {'price': 93.8, 'shipping_rate_price': 0.0},
   'Zeoos': {'price': 96.78, 'shipping_rate_price': 0.0},
   'Global Market 54': {'price': 97.6, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 143.79,
  'ean': '3663792022222',
  'list_other_price': {'GLD Group': {'price': 185.3,
    'shipping_rate_price': 0.0},
   'Microlorge': {'price': 275.75, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 569.99,
  'ean': '0196388146444',
  'list_other_price': {'IT 67 (MSHOP)': {'price': 599.0,
    'shipping_rate_price': 0.0},
   'TOPBIZ': {'price': 623.99, 'shipping_rate_price': 0.0},
   'Gpas Plus': {'price': 631.2, 'shipping_rate_price': 0.0},
   'Pro Componentes': {'price': 620.43, 'shipping_rate_price': 14.9},
   'ASdiscount': {'price': 639.11, 'shipping_rate_price': 0.0},
   'Fexy-shop': {'price': 627.95, 'shipping_rate_price': 12.01},
   'Tienda Tel': {'price': 647.99, 'shipping_rate_price': 3.0},
   'FuturaSell': {'price': 630.0, 'shipping_rate_price': 21.0},
   'yes-Promo': {'price': 639.56, 'shipping_rate_price': 12.11}}},
 {'price_site_seller': 379.99,
  'ean': '0753759232726',
  'list_other_price': {'DistribNet': {'price': 563.84,
    'shipping_rate_price': 0.0},
   'MAGI DISTRIBUTION': {'price': 592.98, 'shipping_rate_price': 0.0},
   'GLD Group': {'price': 593.8, 'shipping_rate_price': 0.0},
   'Detoutpourmoinscher': {'price': 658.7, 'shipping_rate_price': 0.0},
   'TRADEINN': {'price': 659.49, 'shipping_rate_price': 0.0},
   'BRANDS USA': {'price': 1104.0, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 199.99,
  'ean': '3507460183597',
  'list_other_price': {'Full Line OU': {'price': 258.63,
    'shipping_rate_price': 0.0},
   'GLD Group': {'price': 271.0, 'shipping_rate_price': 0.0},
   'Microlorge': {'price': 369.42, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 269.99,
  'ean': '4054278834221',
  'list_other_price': {'Stacca': {'price': 280.99, 'shipping_rate_price': 0.0},
   'UBALDI': {'price': 289.0, 'shipping_rate_price': 0.0},
   'Icoza': {'price': 316.34, 'shipping_rate_price': 0.0},
   'ZOOMICI': {'price': 322.84, 'shipping_rate_price': 0.0},
   'VERKTER': {'price': 326.16, 'shipping_rate_price': 4.99},
   'Trending Utopic': {'price': 332.2, 'shipping_rate_price': 0.0},
   'TRADEINN': {'price': 339.07, 'shipping_rate_price': 0.0},
   'Treat Srores': {'price': 339.79, 'shipping_rate_price': 0.0},
   'Talixe': {'price': 339.79, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 1699.99,
  'ean': '4711377044233',
  'list_other_price': {'GLD Group': {'price': 2151.3,
    'shipping_rate_price': 0.0}}},
 {'price_site_seller': 169.98,
  'ean': '6941812717479',
  'list_other_price': {'futureMall': {'price': 159.0,
    'shipping_rate_price': 0.0},
   'MILife Mall': {'price': 166.99, 'shipping_rate_price': 0.0},
   'ELIAZON': {'price': 164.5, 'shipping_rate_price': 6.0},
   'ALMETECH  France': {'price': 174.99, 'shipping_rate_price': 0.0},
   'Miberia': {'price': 181.0, 'shipping_rate_price': 0.0},
   'DistribNet': {'price': 177.69, 'shipping_rate_price': 8.77},
   'Trending Utopic': {'price': 189.1, 'shipping_rate_price': 0.0},
   'Treat Srores': {'price': 193.35, 'shipping_rate_price': 0.0},
   'Tek4Life': {'price': 195.01, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 269.99,
  'ean': '0045496453596',
  'list_other_price': {'zhangdandantong': {'price': 279.99,
    'shipping_rate_price': 25.0},
   'Boutiquefutee': {'price': 335.4, 'shipping_rate_price': 0.0},
   'stortle': {'price': 341.66, 'shipping_rate_price': 0.0},
   'Avanturis': {'price': 343.48, 'shipping_rate_price': 0.0},
   'MONTCHOIX': {'price': 335.0, 'shipping_rate_price': 10.0},
   'ALPEXE France': {'price': 353.04, 'shipping_rate_price': 0.0},
   'Le Petit KStore': {'price': 354.4, 'shipping_rate_price': 0.0},
   'FuturaSell': {'price': 338.0, 'shipping_rate_price': 18.0},
   'TOPBIZ': {'price': 359.29, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 319.99,
  'ean': '0045496453435',
  'list_other_price': {'GeeksRevolt': {'price': 305.95,
    'shipping_rate_price': 0.0},
   'ELIAZON': {'price': 329.9, 'shipping_rate_price': 6.0},
   'zhangdandantong': {'price': 319.99, 'shipping_rate_price': 25.0},
   'ZOOMICI': {'price': 354.6, 'shipping_rate_price': 0.0},
   'Best Digit': {'price': 342.95, 'shipping_rate_price': 15.0},
   'Jeux Video Du Net': {'price': 364.99, 'shipping_rate_price': 0.0},
   'avotredispo': {'price': 362.54, 'shipping_rate_price': 13.0},
   'Geodemars': {'price': 373.64, 'shipping_rate_price': 10.0},
   'SuperPromos': {'price': 398.32, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 289.24,
  'ean': '5099206057302',
  'list_other_price': {'SK3P': {'price': 249.99, 'shipping_rate_price': 10.0},
   'Le Petit KStore': {'price': 315.61, 'shipping_rate_price': 0.0},
   '1foDiscount': {'price': 315.62, 'shipping_rate_price': 0.0},
   '2KINGS': {'price': 336.47, 'shipping_rate_price': 0.0},
   'Gpas Plus': {'price': 341.4, 'shipping_rate_price': 0.0},
   'To B To C': {'price': 321.46, 'shipping_rate_price': 22.0},
   'Restock System': {'price': 349.3, 'shipping_rate_price': 0.0},
   'yes-Promo': {'price': 352.4, 'shipping_rate_price': 0.0},
   'PCANDCO': {'price': 343.36, 'shipping_rate_price': 9.9}}},
 {'price_site_seller': 348.99,
  'ean': '8806094885699',
  'list_other_price': {'SA Kft': {'price': 369.99, 'shipping_rate_price': 0.0},
   'Neondigital': {'price': 380.0, 'shipping_rate_price': 9.99},
   'Icoza': {'price': 395.1, 'shipping_rate_price': 0.0},
   'Morelenet': {'price': 405.18, 'shipping_rate_price': 0.0},
   'Super 10count': {'price': 406.32, 'shipping_rate_price': 0.0},
   'ALMETECH  France': {'price': 413.99, 'shipping_rate_price': 0.0},
   'Talk-Point': {'price': 422.99, 'shipping_rate_price': 0.0},
   'HEYBIT Store': {'price': 434.9, 'shipping_rate_price': 0.0},
   'TOPBIZ': {'price': 438.99, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 169.99,
  'ean': '6941812716922',
  'list_other_price': {'futureMall': {'price': 159.99,
    'shipping_rate_price': 0.0},
   'Sanmi-fr': {'price': 151.99, 'shipping_rate_price': 8.99},
   'MILife Mall': {'price': 156.99, 'shipping_rate_price': 3.99},
   'Xiaomi Official Store': {'price': 167.0, 'shipping_rate_price': 0.0},
   'Mi Connecte': {'price': 169.99, 'shipping_rate_price': 0.0},
   'ELIAZON': {'price': 164.5, 'shipping_rate_price': 6.0},
   'Yeppon': {'price': 174.99, 'shipping_rate_price': 0.0},
   'arrivapresto': {'price': 180.76, 'shipping_rate_price': 0.0},
   'DistribNet': {'price': 176.29, 'shipping_rate_price': 8.77}}},
 {'price_site_seller': 499.99,
  'ean': '0196786287145',
  'list_other_price': {'Fexy-shop': {'price': 855.35,
    'shipping_rate_price': 0.0},
   'stortle': {'price': 857.49, 'shipping_rate_price': 0.0},
   'GLD Group': {'price': 858.9, 'shipping_rate_price': 0.0},
   'TOPBIZ': {'price': 865.97, 'shipping_rate_price': 0.0},
   'LMD Distribution': {'price': 865.98, 'shipping_rate_price': 0.0},
   'ADMI': {'price': 905.63, 'shipping_rate_price': 0.0},
   'ZOOMICI': {'price': 913.17, 'shipping_rate_price': 0.0},
   'Mon Parc Informatique': {'price': 952.73, 'shipping_rate_price': 0.0},
   'ASdiscount': {'price': 1001.72, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 299.99,
  'ean': '0889842651393',
  'list_other_price': {'ELIAZON': {'price': 268.9, 'shipping_rate_price': 6.0},
   'CW Distribution': {'price': 289.0, 'shipping_rate_price': 0.0},
   'TOPBIZ': {'price': 312.89, 'shipping_rate_price': 0.0},
   'avotredispo': {'price': 299.9, 'shipping_rate_price': 13.0},
   'IT 67 (MSHOP)': {'price': 299.0, 'shipping_rate_price': 0.0},
   'ALPEXE France': {'price': 316.32, 'shipping_rate_price': 0.0},
   'Fexy-shop': {'price': 306.74, 'shipping_rate_price': 12.01},
   'Geodemars': {'price': 308.9, 'shipping_rate_price': 10.0},
   'kaijott': {'price': 314.99, 'shipping_rate_price': 15.0}}},
 {'ean': '8806094733242',
  'list_other_price': {'SSDPRO': {'price': 959.99, 'shipping_rate_price': 0.0},
   'Neondigital': {'price': 992.0, 'shipping_rate_price': 9.99},
   'FutureD': {'price': 1011.9, 'shipping_rate_price': 0.0},
   'TEKSHOP': {'price': 1035.0, 'shipping_rate_price': 0.0},
   'TOPBIZ': {'price': 1142.79, 'shipping_rate_price': 0.0},
   'FuturaSell': {'price': 1130.8, 'shipping_rate_price': 12.0},
   'Tienda Siglo XXI': {'price': 1170.73, 'shipping_rate_price': 16.95},
   'Talk-Point': {'price': 1228.99, 'shipping_rate_price': 0.0},
   'BIG BAZAR 62': {'price': 1299.0, 'shipping_rate_price': 0.0},
   'IT 67 (MSHOP)': {'price': 1299.0, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 174.99,
  'ean': '6934177767333',
  'list_other_price': {'Sanmi-fr': {'price': 158.89,
    'shipping_rate_price': 8.99},
   'MILife Mall': {'price': 163.99, 'shipping_rate_price': 3.99},
   'ELIAZON': {'price': 162.0, 'shipping_rate_price': 6.0},
   'Yeppon': {'price': 182.99, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 115.99,
  'ean': '6941812714959',
  'list_other_price': {'Sanmi-fr': {'price': 113.99,
    'shipping_rate_price': 9.99},
   'MILife Mall': {'price': 124.99, 'shipping_rate_price': 0.0},
   'Yeppon': {'price': 133.99, 'shipping_rate_price': 0.0},
   'ELIAZON': {'price': 131.0, 'shipping_rate_price': 6.0},
   'arrivapresto': {'price': 138.45, 'shipping_rate_price': 0.0},
   'LMD Distribution': {'price': 138.9, 'shipping_rate_price': 0.0},
   'DistribNet': {'price': 130.86, 'shipping_rate_price': 8.77},
   'yes-Promo': {'price': 131.0, 'shipping_rate_price': 8.77}}},
 {'price_site_seller': 25.99,
  'ean': '0195161166969',
  'list_other_price': {'negocie plus': {'price': 26.9,
    'shipping_rate_price': 0.0},
   'Boutiquefutee': {'price': 29.82, 'shipping_rate_price': 0.0},
   'TRADEINN': {'price': 30.89, 'shipping_rate_price': 0.0},
   'yes-Promo': {'price': 22.27, 'shipping_rate_price': 8.77},
   'Consommables-com': {'price': 31.07, 'shipping_rate_price': 0.0},
   'ALPEXE France': {'price': 32.15, 'shipping_rate_price': 0.0},
   'Just shopping': {'price': 32.7, 'shipping_rate_price': 0.0},
   'ASdiscount': {'price': 32.86, 'shipping_rate_price': 0.0},
   'ZOOMICI': {'price': 32.94, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 115.99,
  'ean': '6941812715697',
  'list_other_price': {'futureMall': {'price': 139.0,
    'shipping_rate_price': 0.0},
   'Pro Componentes': {'price': 141.13, 'shipping_rate_price': 9.9},
   'ALMETECH  France': {'price': 153.99, 'shipping_rate_price': 0.0},
   'TRADEINN': {'price': 154.39, 'shipping_rate_price': 0.0},
   'Talk-Point': {'price': 161.99, 'shipping_rate_price': 0.0},
   'ESSEBI SHOP': {'price': 153.0, 'shipping_rate_price': 9.0},
   'ZOOMICI': {'price': 162.02, 'shipping_rate_price': 0.0},
   'Tienda Siglo XXI': {'price': 145.67, 'shipping_rate_price': 16.95},
   'MAX-G-MOBILE SL': {'price': 168.89, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 279.99,
  'ean': '6941812709672',
  'list_other_price': {'MILife Mall': {'price': 255.55,
    'shipping_rate_price': 11.99},
   'Xiaomi Official Store': {'price': 269.0, 'shipping_rate_price': 0.0},
   'Sanmi-fr': {'price': 269.99, 'shipping_rate_price': 0.0},
   'Yeppon': {'price': 297.99, 'shipping_rate_price': 0.0},
   'DistribNet': {'price': 300.95, 'shipping_rate_price': 8.77},
   'Neondigital': {'price': 300.0, 'shipping_rate_price': 9.99},
   'yes-Promo': {'price': 302.2, 'shipping_rate_price': 8.77},
   'Fexy-shop': {'price': 302.39, 'shipping_rate_price': 8.7},
   'Talk-Point': {'price': 311.99, 'shipping_rate_price': 0.0}}},
 {'price_site_seller': 249.0,
  'ean': '8806094534047',
  'list_other_price': {'Pro Componentes': {'price': 243.0,
    'shipping_rate_price': 9.9},
   'Super 10count': {'price': 257.05, 'shipping_rate_price': 0.0},

In [66]:
#info_all_seller_product

In [67]:
info_all_seller_product[0]["list_other_price"]

{'NDR STORE': {'price': 499.0, 'shipping_rate_price': 0.0},
 'ENTER-WEB': {'price': 518.04, 'shipping_rate_price': 0.0},
 'GLD Group': {'price': 698.8, 'shipping_rate_price': 0.0},
 'TOPBIZ': {'price': 708.21, 'shipping_rate_price': 0.0},
 'ADMI': {'price': 759.54, 'shipping_rate_price': 0.0},
 'PCANDCO': {'price': 749.96, 'shipping_rate_price': 10.9},
 'FRANCE/RENEW': {'price': 906.06, 'shipping_rate_price': 0.0}}

In [89]:
product_to_keep

[{'ean': '0196119451311',
  'price': 701.85,
  'margin': 96.58250000000001,
  'shipping_rate_price': 0.0},
 {'ean': '4711121242069',
  'price': 1469.9,
  'margin': 249.42500000000007,
  'shipping_rate_price': 0.0},
 {'ean': '3701542101732',
  'price': 123.1,
  'margin': 4.645,
  'shipping_rate_price': 0.0},
 {'ean': '4710886672340',
  'price': 299.9,
  'margin': 44.924999999999976,
  'shipping_rate_price': 10.0},
 {'ean': '3612408913485',
  'price': 33.92,
  'margin': 7.842000000000003,
  'shipping_rate_price': 0.0},
 {'ean': '0196786486111',
  'price': 1065.3,
  'margin': 155.51499999999996,
  'shipping_rate_price': 0.0},
 {'ean': '3660767979482',
  'price': 291.22,
  'margin': 7.547000000000018,
  'shipping_rate_price': 0.0},
 {'ean': '8806090397424',
  'price': 154.0,
  'margin': 10.910000000000007,
  'shipping_rate_price': 0.0},
 {'ean': '7290112634580',
  'price': 61.92,
  'margin': 12.142,
  'shipping_rate_price': 0.0},
 {'ean': '0196786486081',
  'price': 800.05,
  'margin': 380.05249999999995,
  'shipping_rate_price': 0.0},
 {'ean': '8720389000041',
  'price': 78.71,
  'margin': 7.913499999999994,
  'shipping_rate_price': 0.0},
 {'ean': '3663792022222',
  'price': 185.3,
  'margin': 13.715000000000018,
  'shipping_rate_price': 0.0},
 {'ean': '0753759232726',
  'price': 563.84,
  'margin': 99.27400000000002,
  'shipping_rate_price': 0.0},
 {'ean': '3507460183597',
  'price': 258.63,
  'margin': 19.845499999999987,
  'shipping_rate_price': 0.0},
 {'ean': '4711377044233',
  'price': 2151.3,
  'margin': 128.61500000000018,
  'shipping_rate_price': 0.0},
 {'ean': '0196786287145',
  'price': 855.35,
  'margin': 227.0575,
  'shipping_rate_price': 0.0},
 {'ean': '6941812715697',
  'price': 139.0,
  'margin': 2.1600000000000072,
  'shipping_rate_price': 0.0},
 {'ean': '8806092883628',
  'price': 121.83,
  'margin': 23.565500000000004,
  'shipping_rate_price': 0.0},
 {'ean': '8806092883635',
  'price': 113.55,
  'margin': 6.527500000000003,
  'shipping_rate_price': 0.0},
 {'ean': '8715946702742',
  'price': 85.8,
  'margin': 2.940000000000003,
  'shipping_rate_price': 0.0},
 {'ean': '4711377002103',
  'price': 1355.19,
  'margin': 341.92150000000004,
  'shipping_rate_price': 10.0}]

In [98]:
absolute_threshold = 50
relative_threshold = 0.3
product_to_keep = []
commission = 0.15
for dict_product_info in info_all_seller_product:
    try:
        list_sorted_price_other_seller = [
            v
            for k, v in sorted(
                dict_product_info["list_other_price"].items(), key=lambda x: x[1]["price"] + x[1]["shipping_rate_price"] 
            )
        ]
        margin = (
            list_sorted_price_other_seller[0]["price"] \
            - list_sorted_price_other_seller[0]["shipping_rate_price"] \
            - dict_product_info["price_site_seller"] 
        ) - commission*list_sorted_price_other_seller[0]["price"]
        if margin > 0:
            product_to_keep.append({"ean": dict_product_info["ean"], "price": list_sorted_price_other_seller[0]["price"],"margin": margin, "shipping_rate_price": list_sorted_price_other_seller[0]["shipping_rate_price"]})
        continue
    except Exception as e:
        continue

In [99]:
product_to_keep

[{'ean': '0196119451311',
  'price': 701.85,
  'margin': 96.58250000000001,
  'shipping_rate_price': 0.0},
 {'ean': '4711121242069',
  'price': 1469.9,
  'margin': 249.42500000000007,
  'shipping_rate_price': 0.0},
 {'ean': '3701542101732',
  'price': 123.1,
  'margin': 4.645,
  'shipping_rate_price': 0.0},
 {'ean': '4710886672340',
  'price': 299.9,
  'margin': 44.924999999999976,
  'shipping_rate_price': 10.0},
 {'ean': '3612408913485',
  'price': 33.92,
  'margin': 7.842000000000003,
  'shipping_rate_price': 0.0},
 {'ean': '0196786486111',
  'price': 1065.3,
  'margin': 155.51499999999996,
  'shipping_rate_price': 0.0},
 {'ean': '3660767979482',
  'price': 291.22,
  'margin': 7.547000000000018,
  'shipping_rate_price': 0.0},
 {'ean': '8806090397424',
  'price': 154.0,
  'margin': 10.910000000000007,
  'shipping_rate_price': 0.0},
 {'ean': '7290112634580',
  'price': 61.92,
  'margin': 12.142,
  'shipping_rate_price': 0.0},
 {'ean': '0196786486081',
  'price': 800.05,
  'margin': 380.05249999999995,
  'shipping_rate_price': 0.0},
 {'ean': '8720389000041',
  'price': 78.71,
  'margin': 7.913499999999994,
  'shipping_rate_price': 0.0},
 {'ean': '3663792022222',
  'price': 185.3,
  'margin': 13.715000000000018,
  'shipping_rate_price': 0.0},
 {'ean': '0753759232726',
  'price': 563.84,
  'margin': 99.27400000000002,
  'shipping_rate_price': 0.0},
 {'ean': '3507460183597',
  'price': 258.63,
  'margin': 19.845499999999987,
  'shipping_rate_price': 0.0},
 {'ean': '4711377044233',
  'price': 2151.3,
  'margin': 128.61500000000018,
  'shipping_rate_price': 0.0},
 {'ean': '0196786287145',
  'price': 855.35,
  'margin': 227.0575,
  'shipping_rate_price': 0.0},
 {'ean': '6941812715697',
  'price': 139.0,
  'margin': 2.1600000000000072,
  'shipping_rate_price': 0.0},
 {'ean': '8806092883628',
  'price': 121.83,
  'margin': 23.565500000000004,
  'shipping_rate_price': 0.0},
 {'ean': '8806092883635',
  'price': 113.55,
  'margin': 6.527500000000003,
  'shipping_rate_price': 0.0},
 {'ean': '8715946702742',
  'price': 85.8,
  'margin': 2.940000000000003,
  'shipping_rate_price': 0.0},
 {'ean': '4711377002103',
  'price': 1355.19,
  'margin': 341.92150000000004,
  'shipping_rate_price': 10.0}]

absolute_threshold = 50
relative_threshold = 0.3
product_to_keep = dict()
for dict_product_info in info_all_seller_product:
    try:
        list_sorted_price_other_seller = [
            v
            for k, v in sorted(
                dict_product_info["list_other_price"].items(), key=lambda x: x[1]
            )
        ]
        diff_price = (
            list_sorted_price_other_seller[0] - dict_product_info["price_site_seller"]
        )
        relative_diff = (
            list_sorted_price_other_seller[0] - dict_product_info["price_site_seller"]
        ) / dict_product_info["price_site_seller"]
        if relative_diff > relative_threshold:
            if diff_price > absolute_threshold:
                product_to_keep[str(dict_product_info["ean"])] = (
                    dict_product_info["price_site_seller"] * 1.2
                )
        continue
    except Exception:
        continue

In [101]:
product_to_keep

[{'ean': '0196119451311',
  'price': 701.85,
  'margin': 96.58250000000001,
  'shipping_rate_price': 0.0},
 {'ean': '4711121242069',
  'price': 1469.9,
  'margin': 249.42500000000007,
  'shipping_rate_price': 0.0},
 {'ean': '3701542101732',
  'price': 123.1,
  'margin': 4.645,
  'shipping_rate_price': 0.0},
 {'ean': '4710886672340',
  'price': 299.9,
  'margin': 44.924999999999976,
  'shipping_rate_price': 10.0},
 {'ean': '3612408913485',
  'price': 33.92,
  'margin': 7.842000000000003,
  'shipping_rate_price': 0.0},
 {'ean': '0196786486111',
  'price': 1065.3,
  'margin': 155.51499999999996,
  'shipping_rate_price': 0.0},
 {'ean': '3660767979482',
  'price': 291.22,
  'margin': 7.547000000000018,
  'shipping_rate_price': 0.0},
 {'ean': '8806090397424',
  'price': 154.0,
  'margin': 10.910000000000007,
  'shipping_rate_price': 0.0},
 {'ean': '7290112634580',
  'price': 61.92,
  'margin': 12.142,
  'shipping_rate_price': 0.0},
 {'ean': '0196786486081',
  'price': 800.05,
  'margin': 380.05249999999995,
  'shipping_rate_price': 0.0},
 {'ean': '8720389000041',
  'price': 78.71,
  'margin': 7.913499999999994,
  'shipping_rate_price': 0.0},
 {'ean': '3663792022222',
  'price': 185.3,
  'margin': 13.715000000000018,
  'shipping_rate_price': 0.0},
 {'ean': '0753759232726',
  'price': 563.84,
  'margin': 99.27400000000002,
  'shipping_rate_price': 0.0},
 {'ean': '3507460183597',
  'price': 258.63,
  'margin': 19.845499999999987,
  'shipping_rate_price': 0.0},
 {'ean': '4711377044233',
  'price': 2151.3,
  'margin': 128.61500000000018,
  'shipping_rate_price': 0.0},
 {'ean': '0196786287145',
  'price': 855.35,
  'margin': 227.0575,
  'shipping_rate_price': 0.0},
 {'ean': '6941812715697',
  'price': 139.0,
  'margin': 2.1600000000000072,
  'shipping_rate_price': 0.0},
 {'ean': '8806092883628',
  'price': 121.83,
  'margin': 23.565500000000004,
  'shipping_rate_price': 0.0},
 {'ean': '8806092883635',
  'price': 113.55,
  'margin': 6.527500000000003,
  'shipping_rate_price': 0.0},
 {'ean': '8715946702742',
  'price': 85.8,
  'margin': 2.940000000000003,
  'shipping_rate_price': 0.0},
 {'ean': '4711377002103',
  'price': 1355.19,
  'margin': 341.92150000000004,
  'shipping_rate_price': 10.0}]

In [103]:
path = "/home/mtd/Bureau/Ressistance/MS-Excel/int_off_import_template_215618.iv.xlsx"
df_template = pd.read_excel(path)

/home/mtd/anaconda3/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [168]:
raw_data = pd.read_excel(path, header=None)
header_idx = raw_data[
    raw_data[0].eq('Votre référence / Your reference')
].index.values[0]

/home/mtd/anaconda3/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning:Workbook contains no default style, apply openpyxl's default

In [169]:
clean_data = pd.read_excel(
    io=path, 
    header=3
)

/home/mtd/anaconda3/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning:Workbook contains no default style, apply openpyxl's default

In [226]:
clean_data

,Votre référence / Your reference,EAN (Cdiscount)\nGTIN (Octopia),Sous état du produit / Product condition,Stock,Prix (TTC) / Price (incl.tax),TVA (%) / VAT (%),Eco Part (montant/amount)\n(France),DEA (montant/amount)\n(France),Copie Privée (montant) / Private Copy (amount) \n(France),Chemical Tax \n(montant/amount) \n(Suède/Sweden),"Conditionnement :\nQuantité totale vendue / Packaging, conditioning : \nTotal quantity sold","Conditionnement :\nUnité de vente / Packaging, conditioning : \nSales unit",Prix de référence (TTC) / Reference price (incl.tax),Commentaire offre /\nOffers comment,Mécanique commerciale /\nPromotion type,Début / Start,Unnamed: 16,Fin / End,Unnamed: 18,Remise (%) /\nDiscount (%),Prix de référence (€) (TTC) - Applicable uniquement pour les soldes /\nReference Price (€)(incl.tax) - Applicable only for Sales,S’aligner automatiquement sur la meilleure offre / Automatically set to best offer,Plus bas prix autorisé (€)(TTC)(Prix plancher) / Lowest allowable price (€)(incl.tax) (floor price),Délai de préparation\n(nb jours ouvrés max) / Preparation Time\n(Max working days),Suivi / Tracked (Mandatory),Unnamed: 25,Recommandé / Registered,Unnamed: 27
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Date (jj/mm/aaaa) / Date (dd/mm/yyyy),Heure (hh:mm) /\nHour (hh:mm),Date (jj/mm/aaaa) / Date (dd/mm/yyyy),Heure (hh:mm) /\nHour (hh:mm),NaN,NaN,NaN,NaN,NaN,Principal / Main,Additionnel / Additional,Principal / Main,Additionnel / Additional

In [206]:
list_df = []
for i, product in enumerate(product_to_keep):
    tmp_clean_data = pd.DataFrame({
        "Votre référence / Your reference": "ms-" + product["ean"],
        "EAN (Cdiscount)\nGTIN (Octopia)": int(product["ean"]),
        "Stock": 10,
        "Prix de référence (TTC) / Reference price (incl.tax)": product["price"],
        "Délai de préparation\n(nb jours ouvrés max) / Preparation Time\n(Max working days)": 3,
        "Suivi / Tracked (Mandatory)": product["shipping_rate_price"],
        "ecommandé / Registered": product["shipping_rate_price"],
    }, index=[i])
    list_df.append(tmp_clean_data)

In [207]:
tmp_template = pd.concat(list_df)

In [ ]:
tmp_template.to_excel("/home/mtd/Bureau/Ressistance/MS-Excel/partial_template.xlsx", sheet_name="Fichier Intégration Offre")

In [208]:
tmp_template["EAN (Cdiscount)\nGTIN (Octopia)"].apply(lambda x: len(str(x)))

0     12
1     13
2     13
3     13
4     13
5     12
6     13
7     13
8     13
9     12
10    13
11    13
12    12
13    13
14    13
15    12
16    13
17    13
18    13
19    13
20    13
Name: EAN (Cdiscount)\nGTIN (Octopia), dtype: int64

In [210]:
tmp_template

,Votre référence / Your reference,EAN (Cdiscount)\nGTIN (Octopia),Stock,Prix de référence (TTC) / Reference price (incl.tax),Délai de préparation\n(nb jours ouvrés max) / Preparation Time\n(Max working days),Suivi / Tracked (Mandatory),ecommandé / Registered
0,ms-0196119451311,196119451311,10,701.85,3,0.0,0.0
1,ms-4711121242069,4711121242069,10,1469.90,3,0.0,0.0
2,ms-3701542101732,3701542101732,10,123.10,3,0.0,0.0
3,ms-4710886672340,4710886672340,10,299.90,3,10.0,10.0
4,ms-3612408913485,3612408913485,10,33.92,3,0.0,0.0
5,ms-0196786486111,196786486111,10,1065.30,3,0.0,0.0
6,ms-3660767979482,3660767979482,10,291.22,3,0.0,0.0
7,ms-8806090397424,8806090397424,10,154.00,3,0.0,0.0
8,ms-7290112634580,7290112634580,10,61.92,3,0.0,0.0
9,ms-0196786486081,196786486081,10,800.05,3,0.0,0.0
10,ms-8720389000041,8720389000041,10,78.71,3,0.0,0.0
11,ms-3663792022222,3663792022222,10,185.30,3,0.0,0.0
12,ms-0753759232726,753759232726,10,563.84,3,0.0,0.0
13,ms-3507460183597,3507460183597,10,258.63,3,0.0,0.0
14,ms-4711377044233,4711377044233,10,2151.30,3,0.0,0.0
15,ms-0196786287145,196786287145,10,855.35,3,0.0,0.0
16,ms-6941812715697,6941812715697,10,139.00,3,0.0,0.0
17,ms-8806092883628,8806092883628,10,121.83,3,0.0,0.0
18,ms-8806092883635,8806092883635,10,113.55,3,0.0,0.0
19,ms-8715946702742,8715946702742,10,85.80,3,0.0,0.0
20,ms-4711377002103,4711377002103,10,1355.19,3,10.0,10.0